
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: time
    description: "Queries incremental time"
    columns:
      - name: t_time
        description: "Primary key for table"
        tests:
          - unique
          - not_null
  - name: playing_tests
    description: "Playing with tests"
    columns:
      - name: c_custkey
        description: "Primary key for table"
        tests:
          - unique
          - not_null
      - name: c_mktsegment
        description: "Market segment availabolity"
        tests:
          - accepted_values:
              values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']
 


